version: "2"

run:
  allow-parallel-runners: true
  allow-serial-runners: true

output:
  formats:
    text:
      path: stdout

linters:
  enable:
    - bodyclose
    - decorder
    - goconst
    - gocyclo
    - misspell
    - nakedret
    - revive
    - staticcheck
    - unconvert
    - unparam
  settings:
    decorder:
      dec-order:
        - const
        - var
        - type
        - func
      ignore-underscore-vars: false
      disable-dec-num-check: false
      disable-type-dec-num-check: false
      disable-const-dec-num-check: false
      disable-var-dec-num-check: false
      disable-dec-order-check: false
      disable-init-func-first-check: false
    revive:
      severity: error
      enable-all-rules: true
      rules:
        - name: argument-limit
          arguments:
            - 10
          disabled: false
          exclude:
            - '**/*_test.go'
        - name: function-result-limit
          arguments:
            - 3
          disabled: false
          exclude:
            - '**/*_test.go'
        - name: function-length
          disabled: false
          exclude:
            - '**/*_test.go'
        - name: line-length-limit
          arguments:
            - 130
        - name: cognitive-complexity
          arguments:
            - 15
          disabled: false
          exclude:
            - '**/*_test.go'
        - name: error-strings
          disabled: true
        - name: add-constant
          arguments:
            - allowInts: 0,1,2,3
              allowStrs: '""'
              ignoreFuncs: os\.*,fmt\.*,make
              maxLitCount: "2"
          disabled: true
          exclude:
            - '**/*_test.go'
        - name: exported
          disabled: true
        - name: line-length-limit
          disabled: true
        - name: comment-spacings
          disabled: true
        - name: flag-parameter
          disabled: true
        - name: get-return
          disabled: true
        - name: package-comments
          disabled: true
        - name: unchecked-type-assertion
          disabled: true
        - name: import-alias-naming
          disabled: true
        - name: max-public-structs
          disabled: true
        - name: cyclomatic
          arguments:
            - 15
          disabled: false
          exclude:
            - '**/*_test.go'
        - name: nested-structs
          disabled: true
    staticcheck:
      checks:
        - ST1005
  exclusions:
    generated: lax
    paths:
      - mocks
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - mocks
      - third_party$
      - builtin$
      - examples$
